[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0?file:///home/vidit68/Downloads/Final%20working%20demo%20(1).mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\xaf\0\0\0\0\0\0\0>\0\0\x3\x15\0\0\x2\x12\0\0\0\0\0\x4\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\xaf)

[FullScreen]
pos=@Point(560 1134)
screen=@Rect(0 0 1920 1200)
wide=false

[MainWindow]
ShowRemainingTime=true
adv-controls=0
bgSize=@Size(1920 1038)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x90\0\0\0\x96\0\0\x4\xaf\0\0\x3Q\0\0\x1\x90\0\0\0\x96\0\0\x4\xaf\0\0\x3Q\0\0\0\0\0\0\0\0\x6@\0\0\x1\x90\0\0\0\x96\0\0\x4\xaf\0\0\x3Q)

[RecentsMRL]
list=file:///home/vidit68/Downloads/20260211_124210.mp4, file:///home/vidit68/Downloads/random.mp4, file:///home/vidit68/Downloads/Final%20working%20demo%20(1).mp4, file:///home/vidit68/Downloads/The_History_of_Education.mp4, file:///home/vidit68/Downloads/1.65.0%20source%20code/gorhill-uBlock-689182f/dist/firefox/updates.json, file:///home/vidit68/Downloads/1.65.0%20source%20code/gorhill-uBlock-689182f/dist/firefox/publish-signed-beta.py, file:///home/vidit68/Downloads/1.65.0%20source%20code/gorhill-uBlock-689182f/dist/chromium/publish-stable.js, file:///home/vidit68/Downloads/1.65.0%20source%20code/gorhill-uBlock-689182f/dist/chromium/publish-beta.py, directory:///home/vidit68/Downloads, file:///home/vidit68/Downloads/.zapzap_temp/recording_final.mp4, file:///home/vidit68/recording.mp4, file:///home/vidit68/recording.mkv, file:///home/vidit68/Downloads/video6284922525814100737%20(1).mp4, file:///home/vidit68/Downloads/video6284922525814100737.mp4, file:///home/vidit68/Downloads/video6284922525814100737%20%282%29.mp4, file:///home/vidit68/Downloads/index.mp4
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

[VLM]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3%\0\0\x2\xe\0\0\x6\x36\0\0\x3\xde\0\0\x3%\0\0\x2\xe\0\0\x6\x36\0\0\x3\xde\0\0\0\0\0\0\0\0\x6@\0\0\x3%\0\0\x2\xe\0\0\x6\x36\0\0\x3\xde)
